name: Publish package (npm)

on:
  workflow_call:
    inputs:
      package-name:
        description: The name of the package
        default: ${{github.event.repository.name}}
        type: string
      environment-name:
        description: The name of the environment
        default: npm
        type: string
      node-version:
        description: The NodeJS version
        default: ${{vars.NODE_VERSION || '20'}}
        type: string
      emscripten-version:
        description: The Emscripten version
        default: ${{vars.EMSCRIPTEN_VERSION || '3.1.64'}}
        type: string
      ubuntu-version:
        description: The version of the Ubuntu runner image
        default: ${{vars.UBUNTU_VERSION || '20.04'}}
        type: string
      generate:
        description: Generate the parser artifacts
        default: false
        type: boolean

jobs:
  build_wasm:
    name: Build Wasm binaries
    runs-on: ubuntu-${{inputs.ubuntu-version}}
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{inputs.node-version}}
      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{inputs.emscripten-version}}
      - name: Install dependencies
        run: npm i --omit peer --omit optional
      - name: Regenerate parser
        if: ${{inputs.generate}}
        shell: bash
        run: |
          while read -r grammar; do
            grammar_dir=$(dirname "$grammar")
            cd "$grammar_dir"
            npm x -- tree-sitter generate
            cd - > /dev/null
          done < <(find . -name grammar.js -not -path './node_modules/*' -not -path './.build/*')
      - name: Build Wasm binaries
        shell: bash
        run: |-
          while read -r grammar; do
            npm x -- tree-sitter build --wasm "${grammar%/grammar.js}"
          done < <(find . -name grammar.js -not -path './node_modules/*')
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          path: "*.wasm"
          name: prebuilds-Wasm
          retention-days: 2

  build_node:
    name: Build NodeJS binaries on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-${{inputs.ubuntu-version}}"
          - windows-latest
          - macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{inputs.node-version}}
      - name: Install dependencies
        run: npm i --omit peer --omit optional
      - name: Regenerate parser
        if: ${{inputs.generate}}
        shell: bash
        run: |
          while read -r grammar; do
            grammar_dir=$(dirname "$grammar")
            cd "$grammar_dir"
            npm x -- tree-sitter generate
            cd - > /dev/null
          done < <(find . -name grammar.js -not -path './node_modules/*' -not -path './.build/*')
      - name: Build x64 binary
        run: |
          npm x -- prebuildify --arch x64 --target 20.9.0
      - name: Build arm64 binary (linux)
        if: runner.os == 'Linux'
        run: |
          npm x -- prebuildify-cross -i linux-arm64 --arch arm64 --target 20.9.0
      - name: Build arm64 binary
        if: runner.os != 'Linux'
        run: |
          npm x -- prebuildify --arch arm64 --target 20.9.0
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          path: prebuilds/**
          name: prebuilds-${{runner.os}}
          retention-days: 2